In [ ]:
#1.Debug the given code
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(int)  # Error: Cannot convert 'Thirty' to int

print(df)

In [65]:
#1.Ans-Explanation: The invalid string 'Thirty' is replaced with NaN to handle errors.
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = pd.to_numeric(df['Feature1'], errors='coerce')  # Converts invalid values to NaN

print(df)

   Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       NaN       8.9


In [ ]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value)  # Error: fillna() does not modify in place

print(df)


In [5]:
#2.Explanation: Missing values are filled with the column mean.
import pandas as pd

data = {'A': [1, 2, None],
        'B': [4, None, 6]}

df = pd.DataFrame(data)
df.fillna(df.mean(), inplace=True)  # Use inplace=True to modify the DataFrame

print(df)

     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [ ]:
#3.from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5])  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)


In [11]:
#3.answers
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([[1], [2], [3], [4], [5]])  # Reshape X into 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

print(model.predict([[6]]))  # Predict for new value


[12.]


In [ ]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50])  # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


In [14]:
#4.Answer
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[10],[20],[30],[40],[50]]) #Reshape data into 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [ ]:
#5.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  # Error: Labels should be numeric

model = LogisticRegression()
model.fit(X, y)


In [29]:
#5. Answer
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']

# Convert string labels to numeric
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)  # 1 = 'yes', 0 = 'no'

model = LogisticRegression()
model.fit(X, y_encoded) # Train the model


LogisticRegression()

In [ ]:
#6.import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df['Category'])  # Error: Data should be reshaped
print(encoded)


In [40]:
#6. Answer
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df['Category'].values.reshape(-1, 1)) #Reshape 1D to 2D
print(encoded.toarray())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
#6.1
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0] #Error length

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [1]:
#6.1 Answer
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]  # Correct length

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
#7.from sklearn.linear_model import LogisticRegression

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

model = LogisticRegression()
model.fit(X_train, y_train) 


In [2]:
#7. Answer
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]

# Convert string labels to numeric
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y_train)  # 1 = 'yes', 0 = 'no'

model = LogisticRegression()
model.fit(X_train, y_encoded) # Train the model

LogisticRegression()

In [ ]:
#8.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

model = LinearRegression()
model.fit(X_train, y_train) 


In [3]:
#8. Answer
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

# Create imputer object
imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)

model = LinearRegression()
model.fit(X_train_imputed, y_train) # Train the model


LinearRegression()

In [ ]:
#9.
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

model = DecisionTreeClassifier()
model.fit(X_train, y_train)


In [4]:
#9. Answer
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]

# Convert string labels to numeric
le = LabelEncoder()
y_encoded = le.fit_transform(y_train)  # 0='ham', 1='spam'

model = DecisionTreeClassifier()
model.fit(X_train, y_encoded) # Train the model


DecisionTreeClassifier()

In [ ]:
#10.
from sklearn.svm import SVC

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

model = SVC()
model.fit(X_train, y_train)
print(model.predict([[1, 150]]))  # Unreliable output due to large-scale difference


In [5]:
#10. Answer
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

model = SVC()
model.fit(X_train_scaled, y_train)

# Scale new data point before prediction
X_test_scaled = scaler.transform([[1, 150]])
print(model.predict(X_test_scaled))

[0]


In [ ]:
#11.Why does this train-test split fail?
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1.2, random_state=42)

In [6]:
#11. Answer
test_size=1.2 #invalid value
#Because Must be between zero and one
#ex - test_size=0.2 / test_size=0.8
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
#12.from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1, 0]

model = DecisionTreeClassifier(max_depth=100) #Error: max_depth=100 (Overfitting)
model.fit(X, y)
print(model.score(X, y))

1.0


In [76]:
#12. Answer
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1, 0]

model = DecisionTreeClassifier(max_depth=2)  # max_depth=1 or max_depth=2
model.fit(X, y)
print(model.score(X, y))

1.0


In [ ]:
#13.from sklearn.cluster import KMeans
import numpy as np

X = np.array([[1, 2], [3, 4], [5, 6]])

model = KMeans(n_clusters=5) #Error: (n_clusters=5) This is more than the number of data points
model.fit(X)

In [8]:
#13. Answer
from sklearn.cluster import KMeans
import numpy as np

X = np.array([[1, 2], [3, 4], [5, 6]])

model = KMeans(n_clusters=2)  # 2 clusters <= 3 samples
model.fit(X)

C:\Anaconda\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Anaconda\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
        "wmic CPU Get NumberOfCores /Format:csv".split(),
        capture_output=True,
        text=True,
    )
  File "C:\Anaconda\Lib\subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass

KMeans(n_clusters=2)

In [ ]:
#14.
import padas as pd  #Error: Module name error

df = pd.DataFrame({'A': [1, 2, 3]})
print(df)

In [9]:
#14. Answer
import pandas as pd  

df = pd.DataFrame({'A': [1, 2, 3]})
print(df)

   A
0  1
1  2
2  3


In [ ]:
#15.from sklearn.tree import DecisionTreClassifier  # Typo in 'DecisionTreeClassifier'

from sklearn.tree import DecisionTreClassifier  # Typo in 'DecisionTreeClassifier'

model = DecisionTreClassifier() #spelling mistakes

In [10]:
#15. Answer
from sklearn.tree import DecisionTreeClassifier #correct spelling

model = DecisionTreeClassifier() #correct spelling

In [ ]:
#16.
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(depth=3)  #Error: DecisionTreeClassifier does not have a depth parameter

In [11]:
#16. Answer
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(max_depth=3)  #correct parameter name - max_depth 

In [ ]:
#17.
from sklearn.linear_model import LinearRegression

X = [[1], [2], [3], [4]]
y = [2, 4, 6, 8]

model = LinearRegression()
model.fit(X, y)

print(model.coef)  # Incorrect attribute name

In [12]:
#17. Answer
from sklearn.linear_model import LinearRegression

X = [[1], [2], [3], [4]]
y = [2, 4, 6, 8]

model = LinearRegression()
model.fit(X, y)

print(model.coef_) #correct attribute

[2.]


In [ ]:
#18.
from sklearn.neighbors import KNeighborsClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = [0, 1, 0]

model = KNeighborsClassifier(n_neighbors=0)  # Invalid value for n_neighbors
model.fit(X_train, y_train)

In [13]:
#18. Answer
from sklearn.neighbors import KNeighborsClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = [0, 1, 0]

model = KNeighborsClassifier(n_neighbors=5) #n_neighbors ≥ 1 (at least one neighbor required)
model.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
#19.
import pandas as pd

df = pd.DataFrame({'A': [10, 20, 30], 'B': [1, 2, 3]})
print(df.iloc['A'])  # Incorrect: iloc requires integer indexes

In [14]:
#19. Answer
import pandas as pd

df = pd.DataFrame({'A': [10, 20, 30], 'B': [1, 2, 3]})
print(df.iloc[2]) # iloc - For numeric codes only

A    30
B     3
Name: 2, dtype: int64


In [ ]:
#20.
from sklearn.ensemble import RandomForestClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = [0, 1, 0]

model = RandomForestClassifier()
model.fit(X_train, y_train)

probs = model.predict_proba([[2, 3]])[1]  # Incorrect index
print(probs)

In [15]:
#20. Answer
from sklearn.ensemble import RandomForestClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = [0, 1, 0]

model = RandomForestClassifier()
model.fit(X_train, y_train)

probs = model.predict_proba([[2, 3]])[0]  
print(probs)

[0.76 0.24]
